# Generated by Django 3.0 on 2022-03-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE')], default='TODO', max_length=10)),
            ],
        ),
    ]
